apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    # Argo CD UI: dùng cùng repo Git và revision mà bạn đã cấu hình
    repoURL: https://github.com/Daonguyen2401/MLPlatform.git
    targetRevision: HEAD
    path: kserve-crd
    helm:
      releaseName: kserve-crd
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

