apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-models-web-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/Daonguyen2401/MLPlatform.git
    targetRevision: HEAD
    path: kserve-model-web-app/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
